### ISSUE TITLE
Web Performance

### ISSUE THREAD

**Issue by lilbaj** [drew0036/web-design-2-independent-project#3]
<img width="1020" alt="Screen Shot 2020-12-11 at 1 45 33 PM" src="https://user-images.githubusercontent.com/55108804/101942326-59686580-3bb7-11eb-8ac7-1aaeaef3dada.png">
<img width="1020" alt="Screen Shot 2020-12-11 at 1 46 02 PM" src="https://user-images.githubusercontent.com/55108804/101942330-5b322900-3bb7-11eb-9af9-8db70475ae39.png">

hey holly, 
great job, maybe just check to make sure all your images are compressed. I think thats it though, your test score is about the same as a lot of other peoples so great work!

**Comment by drew0036** [comment]
Thank you!
