### ISSUE TITLE
Mircosoft Edge 

### ISSUE THREAD

**Issue by NikCasar** [drew0036/web-design-2-independent-project#4]
1. on the largest screen size the fonts are very small and hard to read.

2. On the largest screen size, your "legal vs illegal opioids?" is off to the side, the paragraph hang off a bit it looks off a bit but that might just be me. 

3. proably just my prefence but I feel like the second nav is alot, maybe there's a better way of displaying it. To me it just seems like alot of scrolling back up, maybe if you had it as a side bar nav that was permafixed to the side to follow the scrolling instead of having to scroll back up if you wanted to find a certain part. Just my opinon, don't feel as if you have to change it :)    

otherwise it checks out on microsoft edge, I really like the design. It's very infromative and it gives that tone of a goverment information website ( I hope that's what you were going for). -Nikki

**Comment by drew0036** [comment]
Exactly what I was going for, thank you!
