### ISSUE TITLE
Firefox Desktop

### ISSUE THREAD

**Issue by emfeather94** [drew0036/web-design-2-independent-project#7]
- Your site looks so professional !
- Your first three links work great, I assume the rest are for later :) 
- on desktop I might suggest having everything in 1 column with the same line length (left aligned but entered to the page) or slightly smaller line lengths if you stay with the 2 column but push in the sides a bit so its more centred to the screen (easier to read)
- Really impressed with all the work you’ve put into it!
- responsive to screen sizes

**Comment by drew0036** [comment]
Thank you!
